const GROUPS=[
{n:1,title:'시작 전 준비',en:'Preliminaries',description:'개발 도구 설치와 서비스 계정 준비',badge:'준비',ids:['setup']},
{n:2,title:'무엇을, 어떻게 만들까?',en:'Introduction',description:'CoverLetterIDE 소개 · PRD와 스펙으로 설계하기',badge:'설계',ids:['intro','prd']},
{n:3,title:'만들면서 만나는 기초 개념',en:'Fundamentals',description:'Git · 웹 구조 · AI 모델 · OAuth와 JWT',badge:'개념',ids:['git','web','ai','auth']},
{n:4,title:'직접 웹사이트 만들기',en:'Hands-on',description:'목업부터 배포, 로그인, AI 시스템 연결까지',badge:'실습',ids:['practice','deploy','login','agent']},
{n:5,title:'판단은 결국 우리의 몫',en:'Reflection',description:'좋은 피드백의 기준과 설계자의 책임',badge:'생각',ids:['reflection']}
];
const nav=document.getElementById('navigation');
nav.innerHTML=`<a href="#overview" class="nav-main" data-route="overview"><span class="num">⌂</span>전체 커리큘럼</a>`+GROUPS.map(g=>`<a class="nav-main" data-group="${g.n}" href="#${g.ids[0]}"><span class="num">0${g.n}</span>${g.title}</a>${g.ids.map(id=>`<a class="nav-sub" href="#${id}" data-route="${id}">${({setup:'설치와 회원가입',intro:'함께 만들 프로젝트',prd:'PRD · SDD',git:'Git · GitHub',web:'웹 개발의 기본 구조',ai:'LLM · Embedding · Jev',auth:'OAuth · JWT',practice:'PRD와 프론트엔드 목업',deploy:'Cloudflare에 배포',login:'Google 로그인 연결',agent:'AI 시스템 만들기',reflection:'우리가 확인해야 할 것'})[id]}</a>`).join('')}`).join('');
function overview(){return `<div class="eyebrow">VIBE CODING WORKSHOP <span class="pill">개념 + 실습</span></div><div class="intro-grid"><div><h1>직접 만들면서 배우는<br><em>바이브코딩</em></h1><p class="lead">AI에게 맡길 줄 아는 것에서,<br>함께 만든 것을 이해하는 것까지.<br>자소서 서비스를 만들며 웹 개발의 큰 그림을 익힙니다.</p><div class="tags"><span class="tag">개발 입문자</span><span class="tag">VS Code + Codex</span><span class="tag">CoverLetterIDE</span></div></div><div><div class="mock" role="img" aria-label="CoverLetterIDE의 세 영역: 파일 탐색기, 자소서 편집기, AI 코치"><div class="mock-bar"><span>○ ○ ○</span><span>CoverLetterIDE / workspace</span><span>⋯</span></div><div class="mock-top">나의 첫 자기소개서<span>오늘 만들 프로젝트</span></div><div class="mock-panes"><div class="mock-pane"><strong>파일 탐색기</strong>▱ 내 프로필<br>▱ 경험 정리<br><span style="color:#d9f19f">▤ 지원 동기</span></div><div class="mock-pane"><strong>지원 동기를 작성해 주세요.</strong><div class="mock-line"></div><div class="mock-line"></div><div class="mock-line"></div><div class="mock-line" style="width:85%"></div><div class="mock-line" style="width:50%"></div></div><div class="mock-pane"><strong>✧ AI 코치</strong><div class="mock-note">경험과 직무를<br>연결해 볼까요?</div><div class="mock-line"></div><div class="mock-line"></div></div></div><div class="mock-footer"><span>작성 · 피드백 · 개선</span><span>CONCEPT PREVIEW</span></div></div><div class="mock-caption">한 화면에서 자료 탐색, 자소서 작성, AI 피드백</div></div></div><div class="ribbon"><strong>이렇게 함께 배워요</strong><span>개념을 이해하고, 바로 작은 실습으로 연결합니다. 에이전트가 작업하는 동안 다음 개념을 살펴보세요.</span></div><div class="section-head"><h2>오늘의 학습 여정</h2><span>5개 챕터 · 12개 수업 노트</span></div><div class="curriculum">${GROUPS.map(g=>`<a href="#${g.ids[0]}" class="chapter-card"><span class="chapter-num">0${g.n}</span><div><h3>${g.title}<span>${g.en}</span></h3><p>${g.description}</p></div><span class="badge ${g.n===4?'practice':''}">${g.badge}</span></a>`).join('')}</div><div class="start-row"><a href="#setup" class="button">수업 준비부터 시작하기</a><p>처음이라면 순서대로, 복습할 때는 필요한 개념부터.</p></div>`}
function lessonPage(l){const index=LESSONS.indexOf(l),prev=index>0?LESSONS[index-1]:null,next=LESSONS[index+1];return `<div class="lesson-layout"><article class="lesson-body"><div class="lesson-top"><div class="eyebrow">CHAPTER 0${l.group} <span>/</span> ${l.en}</div><h1>${l.title}</h1><p class="lead">${l.intro}</p><div class="reading-note">${GROUPS[l.group-1].title} · ${l.sections.length}가지 핵심 주제</div></div>${l.sections.map(([id,t,html],i)=>`<section id="${id}"><h2><span class="section-index">0${i+1}</span>${t}</h2>${html}</section>`).join('')}<div class="sources"><strong>더 살펴보기</strong>${l.sources.map(([url,t])=>`<a href="${url}" target="_blank" rel="noopener">${t}</a>`).join('')}</div><div class="nav-bottom"><a href="#${prev?prev.id:'overview'}"><small>이전 노트</small>${prev?prev.title:'전체 커리큘럼'}</a><a class="button secondary" href="#${next?next.id:'overview'}">${next?'다음 · '+next.title:'전체 커리큘럼으로'}</a></div></article><aside class="toc" aria-label="현재 노트 목차"><strong>이 노트에서</strong>${l.sections.map(([id,t],i)=>`<a href="#${l.id}/${id}"><span class="mono">0${i+1}</span> ${t}</a>`).join('')}<div style="border-top:1px solid var(--line);margin-top:25px;padding-top:12px;color:#9ba48f">개념을 읽고<br>내 말로 설명해 보세요.</div></aside></div>`}
let current='';
function route(){const [raw,anchor]=location.hash.slice(1).split('/');const id=raw||'overview';const l=LESSONS.find(x=>x.id===id);const effective=l?id:'overview';const changed=current!==effective;current=effective;
if(changed){document.getElementById('content').innerHTML=l?lessonPage(l):overview();document.title=(l?l.title:'함께 만들며 이해하기')+' — 바이브코딩 클래스';document.getElementById('breadcrumb').innerHTML=l?`<a href="#overview">수업 노트</a> <span>/</span> ${GROUPS[l.group-1].title}`:'수업 안내 <span>/</span> 전체 커리큘럼';document.querySelectorAll('[data-route]').forEach(a=>{const active=a.dataset.route===effective;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.querySelectorAll('[data-group]').forEach(a=>a.classList.toggle('active',l&&Number(a.dataset.group)===l.group));window.scrollTo({top:0,behavior:'instant'});}
if(anchor&&l&&l.sections.some(s=>s[0]===anchor)){requestAnimationFrame(()=>document.getElementById(anchor)?.scrollIntoView({behavior:'smooth'}));}
closeMenu();}
const sidebar=document.getElementById('sidebar'),menu=document.getElementById('menu');
function closeMenu(){sidebar.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','수업 목차 열기')}
menu.addEventListener('click',()=>{const open=sidebar.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'수업 목차 닫기':'수업 목차 열기')});
document.addEventListener('click',async e=>{if(sidebar.classList.contains('open')&&!sidebar.contains(e.target)&&!menu.contains(e.target))closeMenu();if(e.target.closest('#navigation a'))closeMenu();const b=e.target.closest('.copy');if(!b)return;const text=b.closest('.code-block').querySelector('code').textContent;try{await navigator.clipboard.writeText(text);const originalLabel=b.textContent;b.textContent='복사됨';notify('클립보드에 복사했습니다.');setTimeout(()=>{b.textContent=originalLabel},1800)}catch{notify('자동 복사가 지원되지 않습니다. 코드 내용을 선택해 복사해 주세요.')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
let toastTimer;function notify(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2600)}
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();document.getElementById('content').focus();});
window.addEventListener('hashchange',route);route();
